AllCops:
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Exclude:
    - "lib/generators/**/*"

Metrics/MethodLength:
  Exclude:
    - "lib/generators/**/*"
    - "test/**/*"

Metrics/AbcSize:
  Exclude:
    - "lib/generators/**/*"
    - "test/**/*"

Naming/MethodParameterName:
  inherit_mode:
    merge:
      - AllowedNames
  AllowedNames:
    - fs
